### ISSUE TITLE
fails to start

### ISSUE THREAD

**Issue by noledge** [huwwp/cryptop#9]
```
$ cryptop 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cryptop-0.1.1-py3.4.egg/cryptop.py", line 116, in read_wallet
    with open(datafile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.cryptop/wallet.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 9, in <module>
    load_entry_point('cryptop==0.1.1', 'console_scripts', 'cryptop')()
  File "/usr/local/lib/python3.4/dist-packages/cryptop-0.1.1-py3.4.egg/cryptop.py", line 219, in main
    curses.wrapper(mainc)
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/cryptop-0.1.1-py3.4.egg/cryptop.py", line 174, in mainc
    wallet = read_wallet()
  File "/usr/local/lib/python3.4/dist-packages/cryptop-0.1.1-py3.4.egg/cryptop.py", line 118, in read_wallet
    except (FileNotFoundError, json.decoder.JSONDecodeError):
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

installed via pip and setup.py on a raspberry pi running raspbian.

**Comment by noledge** [comment]
Reading the source, the missing wallet.json is fine on first startup and should be written then - but it fails, because of missing JSONDecodeError (which seems to be added in python 3.5 and thus not working in python 3.4). Removing it to

`except (FileNotFoundError):
`
and the wallet file is written just fine and the program works as expected.

**Comment by cclauss** [comment]
What versions of Python are supported?  `FileNotFoundError` was not defined in Python 2.

flake8 testing of https://github.com/huwwp/cryptop on __Python 2.7.13__

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./cryptop.py:118:10: F821 undefined name 'FileNotFoundError'
	except (FileNotFoundError, json.decoder.JSONDecodeError):
                ^
```

**Comment by noledge** [comment]
The readme states "Please note cryptop requires Python 3 to run.", so I would assume that Python 2 makes problems.
My issue is that even 3.4 does not work with the current code, as JSONDecodeError is from Python 3.5

**Comment by huwwp** [comment]
Thank you, I changed it to a generic ValueError which JSONDecodeError is a subclass of. Also added a note in the readme that I've only tested on 3.6 so far
